name: CI - Test Package

on:
  workflow_call:
    inputs:
      packages:
        description: 'YAML array containing IDs of the packages'
        required: true
        type: string

jobs:
  test-packages:
    strategy:
      fail-fast: false
      matrix:
        package-name: ${{ fromJson(inputs.packages) }}
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Add New Package Source
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: source add --name='repo' --source='./nupkgs/' --priority='1'
      - name: Install ${{ matrix.package-name }}
        uses: crazy-max/ghaction-chocolatey@v1
        timeout-minutes: 3
        continue-on-error: true
        with:
          args: install ${{ matrix.package-name }} -dvy
      - name: Uninstall ${{ matrix.package-name }}
        uses: crazy-max/ghaction-chocolatey@v1
        continue-on-error: false
        with:
          args: uninstall ${{ matrix.package-name }} -dvy
